### ISSUE TITLE
Rigid and Soft body simulation

### ISSUE THREAD

**Issue by frading** [polygonjs/polygonjs#2]
integrate a library like Ammo or Cannon.

Simulated objects setup could be done with a few nodes, such as RBDPrepare and RBDSolver. Optional nodes could create low res hulls if needed.

**Comment by fire** [comment]
https://socket.dev/npm/package/jolt-physics has rigid and soft body support too.

Was familiar as Jolt Physics is in the Godot Engine channels.

**Comment by frading** [comment]
Looks like it's was time for me to clean those outstanding issues, as a few of them should have been closed.

This is the case for this one, as polygonjs now has RBD solver, using rapier ( [see examples](https://polygonjs.com/docs/nodes/sop/PhysicsWorld) or [source of the main solver now](https://github.com/polygonjs/polygonjs/blob/master/src/engine/nodes/sop/PhysicsWorld.ts) ), and a soft body solver, with its tetrahedralizer, based on [10 min physics](https://github.com/matthias-research/pages/blob/master/tenMinutePhysics/10-softBodies.html)  ( no examples yet, but here is the [main solver node source](https://github.com/polygonjs/polygonjs/blob/master/src/engine/nodes/sop/TetSoftBodySolver.ts) ).

And while those 2 solvers are available, they do not interact with one another.

With that in mind, I only heard about Jolt Physics recently, and had not checked it out, so thank you for the link. It is definitely interesting to consider, but changing what I have with rapier now to another solver would need to bring in substantial benefits. For instance, is there a noticeable performance gain?

I'll keep this open for now, as I'm curious to know more about jolt.

**Comment by fire** [comment]
I would pick one solver like rapier and be done. The issue was out of date.
