### ISSUE TITLE
wrong "Local Export" path

### ISSUE THREAD

**Issue by rozek** [polygonjs/polygonjs#64]
I just created a new PolygonJS project and started the editor.

Then I tried to export the shown scene (the shiny sphere on a checkerboard). The first attempt failed (complaining about a missing `npm install`, which I did)

The second attempt reported that the export would be up-to-date, showed the export path and offered the local export to be opened - which failed

Possible reason: the reported path is `./public/polygonjs/build/scene_01`, but actually, the files can be found in `./public/polygonjs/scenes/scene_01`

**Comment by rozek** [comment]
FYI: the docs (https://polygonjs.com/docs/export/local) seem to show the correct export path

**Comment by frading** [comment]
Yes, I think that this export panel brought confusion. It was a legacy option, as now the recommended way to export is to use `yarn create polygonjs` or `npm run polygonjs@latest`, and then run `yarn build` or `npm run build`.

The export panel was still there as I had not fully migrated the way to upload a build online, which is useful when importing a polygonjs scene in a site builder like Webflow. But I've just completed that, and the export panel has been updated to reflect it, with a links to a new tutorial on how to upload to [AWS S3](https://polygonjs.com/docs/integrations/s3) and the updated [Webflow integration](https://polygonjs.com/docs/integrations/webflow).

![image](https://github.com/polygonjs/polygonjs/assets/59701/de7fa30b-33ae-4234-b4f1-c9905f499b55)

Note that I've substantially updated the templates created with the [cli tool](https://polygonjs.com/docs/install/new) ( [see changes](https://github.com/polygonjs/create-polygonjs/commit/8d3dee174ce6f3c1c079bfdd0c6344d11afaa833) ), so you would need to create a project with the last version to benefit from those changes.
